version: '3.3'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  referral_system:
    build:
      context: ../referral_system
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../referral_system/static/:/static/
    depends_on:
      - referral_system

volumes:
  db_value: